### ISSUE TITLE
Field for entering "flow family" missing in dataset management

### ISSUE THREAD

**Issue by Ecoxl** [Ecoxl/celero#30] opened 2019-01-08 08:12 UTC
flow family is always set on "others" in dataset management.  In older Celero version we may had the field , but took it because we thougt it is not necessary. But Its required for industrial symbiosis.

**Comment by Ocimum-basilicum** [comment] 2019-01-18 13:47
Closing because I cannot reproduce this issue. The flow family field appears when creating a new flow. For flows that already exist its hidden because the family is defined on creation and can't be changed.

**Closed by Ocimum-basilicum** 2019-01-18 13:47 UTC
